# Air configuration for Go hot reload
delay = 1000

[build]
  cmd = "go build -o ./tmp/main main.go"
  bin = "tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor"]
  log = "air.log"

[log]
  color = "true"
