version: '3.8'
services:
  ayo-mwr:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ayo-mwr-dev
    working_dir: /app
    command: >
      sh -c "\
        go install github.com/air-verse/air/v2@latest && \
        air -c .air.toml || go run main.go\
      "
    volumes:
      - ./:/app
      - ./videos:/app/videos
      - ./recordings:/app/recordings
      - ./data:/app/data
    env_file:
      - .env
    ports:
      - "3000:3000"
    tty: true
