name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags (e.g., v1.0.0)
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            ext: ''
            artifact_name: ayo-mwr-linux-amd64
          - goos: windows
            ext: '.exe'
            artifact_name: ayo-mwr-windows-amd64.exe

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        check-latest: true
    
    - name: Set up environment
      run: |
        echo "${{ secrets.ENV_FILE }}" | base64 -d > .env
      shell: bash

    - name: Set up build tools
      run: |
        sudo apt-get update
        if [ "${{ matrix.goos }}" = "windows" ]; then
          sudo apt-get install -y gcc-mingw-w64-x86-64
        fi
        
    - name: Build
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: amd64
        CGO_ENABLED: 1
      run: |
        mkdir -p build
        if [ "${{ matrix.goos }}" = "windows" ]; then
          CC=x86_64-w64-mingw32-gcc GOOS=windows GOARCH=amd64 CGO_ENABLED=1 go build -o "build/${{ matrix.artifact_name }}"
        else
          go build -o "build/${{ matrix.artifact_name }}"
        fi

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: build/${{ matrix.artifact_name }}
        if-no-files-found: error
        retention-days: 7

  release:
    name: Create Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: ayo-mwr-*
          merge-multiple: true

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/ayo-mwr-linux-amd64
            artifacts/ayo-mwr-windows-amd64.exe
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
