name: Release Linux AMD64

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
          
    - name: Install dependencies
      run: go mod download
      
    - name: Run tests
      run: go test -v ./...
      
    - name: Build for Linux AMD64
      env:
        GOOS: linux
        GOARCH: amd64
        CGO_ENABLED: 1
      run: |
        go build -ldflags="-s -w -X main.version=${{ github.ref_name }}" -o ayo-mwr-linux-amd64 .
        
    - name: Create release package
      run: |
        mkdir -p release
        cp ayo-mwr-linux-amd64 release/
        cp README.md release/
        cp env.template release/
        cp -r dashboard release/
        cp -r docs release/
        tar -czf ayo-mwr-linux-amd64.tar.gz -C release .
        
    - name: Generate checksums
      run: |
        sha256sum ayo-mwr-linux-amd64.tar.gz > ayo-mwr-linux-amd64.tar.gz.sha256
        sha256sum ayo-mwr-linux-amd64 > ayo-mwr-linux-amd64.sha256
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ayo-mwr-linux-amd64.tar.gz
          ayo-mwr-linux-amd64.tar.gz.sha256
          ayo-mwr-linux-amd64
          ayo-mwr-linux-amd64.sha256
        draft: false
        prerelease: false
        generate_release_notes: true
        body: |
          ## Release Notes
          
          ### Features
          - Linux AMD64 binary release
          - OTA update capability
          
          ### Installation
          ```bash
          # Download dan ekstrak
          wget https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/ayo-mwr-linux-amd64.tar.gz
          tar -xzf ayo-mwr-linux-amd64.tar.gz
          
          # Jalankan aplikasi
          ./ayo-mwr-linux-amd64
          ```
          
          ### Checksums
          Verifikasi integritas file dengan checksum yang disediakan.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 